import socket
from collections import deque
import json
import threading
import time
import sys


HOST = '192.168.1.25'
PORT = 8000
commands = deque()
out = deque()
temperature = 0
def updater():
    global temperature
    while True:
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.settimeout(5)
            s.connect((HOST, PORT))
            while True:
                to_send = []
                while len(commands) > 0:
                    to_send.append(commands.popleft())
                
                s.sendall(json.dumps(to_send).encode('utf-8'))
                ln = int.from_bytes(s.recv(100), 'big')
                s.send(b"ok")
                raw = s.recv(200*250*200)
                while len(raw) < ln:
                    raw += s.recv(200*250*200)
                
                data = json.loads(raw.decode('utf-8'))
                temperature = data['temp']
                for line in data.get('logs', []):
                    out.append(line)
                
                time.sleep(0.1)
        except Exception as e:
            print('reconnect', e)
            time.sleep(0.5) # Пауза перед переподключением
        finally:
            try: s.close()
            except: pass

def printer():
    while True:
        while len(out) > 0:
            
            #sys.stdout.write(out.popleft())
            print(out.popleft(), end='', flush=True)
        time.sleep(0.01)





def reader():
    print("Commands: 'on', 'off', 'kill' or bash text")
    while True:
        cmd = input()
        if cmd == 'on':
            commands.append(["Turn_relay_ON"])
        elif cmd == 'off':
            commands.append(["Turn_relay_OFF"])
        elif cmd == 'kill':
            commands.append(["poweroff"])
        elif cmd == 'temp':
            print(temperature)
        elif cmd == 'led on':
            commands.append(["Turn_led_ON"])
        elif cmd == 'led off':
            commands.append(["Turn_led_OFF"])
        elif cmd == 'random':
            commands.append(["random"])
        elif cmd == 'r':
            commands.append(["Command_to_execute",  "reboot\n"])
        else:

            
            commands.append(["Command_to_execute", cmd + '\r\n'])

# Запуск
threading.Thread(target=updater).start()
threading.Thread(target=printer).start()

try:
    reader()
except KeyboardInterrupt:
    print("\nExit...")


    """
    
    
    pi@raspberrypi:~$ sudo mount -o remount,rw /boot
mount: /boot: mount point not mounted or bad option.
       dmesg(1) may have more information after failed mount system call.
mount: (hint) your fstab has been modified, but systemd still uses
       the old version; use 'systemctl daemon-reload' to reload.
DO NOT EDIT THIS FILE

The file you are looking for has moved to /boot/firmware/cmdline.txt


    
    
    
    
    
    """